name = "Bioinformatics_Algorithms"
authors = ["FishAres"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DrWatson = "2.14.1"
julia = "1.10.0"
